### ISSUE TITLE
Pytwoway with ONLY continuous controls

### ISSUE THREAD

**Issue by klintmane1** [tlamadon/pytwoway#43] opened 2022-10-26 18:03 UTC
I was wondering if it would be possible to estimate the corrected model with 3 continuous controls instead of some of the controls being categorical. Is this doable? If so, what would I need to change? I suspect the parameters below would need to be changed. Thanks! 

FE

fecontrol_params = tw.fecontrol_params(
    {
        'he': True,
        'continuous_controls': 'cts_control',
        'Q_var': [
            tw.Q.VarCovariate('psi'),
            tw.Q.VarCovariate('alpha'),
            tw.Q.VarCovariate('cts_control'),
            tw.Q.VarCovariate(['psi', 'alpha'])
                 ],
        'ncore': 8
    }
)

**Comment by adamoppenheimer** [comment] 2022-10-26 18:51
Hi Klint,

Do you mean you want to set `psi` and `alpha` to be continuous? That is not currently possible, but may be possible in a future release. I don't think it's particularly useful in general though, since from what I understand, the bias only arises when you are using high dimensional fixed effects models, so if you have only 3 continuous variables there shouldn't be a need to bias-correct the variance estimates.

If that is not what you mean, could you please clarify what you want to do?

**Comment by klintmane1** [comment] 2022-10-26 19:01
Hi Adam! 

Thanks for the quick reply. I think I was not clear as to what I want to do. 

The data you provide for FE with Controls looks like this: 
![Screen Shot 2022-10-26 at 2 57 36 PM](https://user-images.githubusercontent.com/64566056/198113045-9bbc54ee-21b4-48f0-b02d-09331f1cb2ac.png)

I was wondering if I can run the same model with a dataset that looks like this: 
![Screen Shot 2022-10-26 at 2 59 36 PM](https://user-images.githubusercontent.com/64566056/198113306-f72da000-f156-45ed-87d6-98fa9200f019.png)

So instead of having [cat_control1 | cat_control2 | cts_control1 | cts_control2] I have [cts_control1 | cts_control2 | cts_control3]. I want to add 3 control variables. All of them are continuous and there are no categorical control variables. Everything else remains the same.

**Comment by adamoppenheimer** [comment] 2022-10-26 19:06
Yes, this is possible.

Have you tried code for this and it's not working? If so, feel free to post it here and I can take a look and see if I can figure out why it's not working.

**Comment by klintmane1** [comment] 2022-10-26 19:17
I am writing the code below. Let me know if you would prefer me to upload my jupyter notebook file. I tried troubleshooting this by changing the fecontrol_params, by excluding the cat_controls but it did not work. The data I am using is fake data you have provided and I add three random controls. This is to mimic my real data. Thanks for all the help!


# Imports
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)
import pytwoway as tw
import bipartitepandas as bpd

# Load data into Pandas DataFrame
df = pd.read_csv('/Users/klintmane1/Downloads/twoway_sample_data.csv')

# Adding control variables
df['cts_control1']= np.random.randint(0,10, size=len(df))
df['cts_control2']= np.random.randint(0,50, size=len(df))
df['cts_control3']= np.random.randint(0,100, size=len(df))
df

![](https://user-images.githubusercontent.com/64566056/198113306-f72da000-f156-45ed-87d6-98fa9200f019.png)

# FE

fecontrol_params = tw.fecontrol_params(
    {
        'he': True,
        'categorical_controls': 'cat_control',
        'continuous_controls': 'cts_control',
        'Q_var': [
            tw.Q.VarCovariate('psi'),
            tw.Q.VarCovariate('alpha'),
            tw.Q.VarCovariate('cat_control'),
            tw.Q.VarCovariate('cts_control'),
            tw.Q.VarCovariate(['psi', 'alpha']),
            tw.Q.VarCovariate(['cat_control', 'cts_control'])
                 ],
        'Q_cov': [
            tw.Q.CovCovariate('psi', 'alpha'),
            tw.Q.CovCovariate('cat_control', 'cts_control'),
            tw.Q.CovCovariate(['psi', 'alpha'], ['cat_control', 'cts_control'])
        ],
        'ncore': 8
    }
)
# Cleaning
clean_params = bpd.clean_params(
    {
        'connectedness': 'leave_out_spell',
        'collapse_at_connectedness_measure': True,
        'drop_single_stayers': True,
        'drop_returns': 'returners',
        'copy': False
    }
)


# Convert into BipartitePandas DataFrame
bdf = bpd.BipartiteDataFrame(df, track_id_changes=True)
# Clean and collapse
bdf = bdf.clean(clean_params)

# Initialize FE estimator
fe_estimator = tw.FEControlEstimator(bdf, fecontrol_params)
# Fit FE estimator
fe_estimator.fit()
# Investigate results
print(fe_estimator.summary)
![Screen Shot 2022-10-26 at 3 14 33 PM](https://user-images.githubusercontent.com/64566056/198116194-67f3b148-1062-408f-986d-e7be18c365f5.png)

**Comment by adamoppenheimer** [comment] 2022-10-26 19:24
Your issue is here:

```python
fecontrol_params = tw.fecontrol_params(
{
'he': True,
'categorical_controls': 'cat_control',
'continuous_controls': 'cts_control',
'Q_var': [
tw.Q.VarCovariate('psi'),
tw.Q.VarCovariate('alpha'),
tw.Q.VarCovariate('cat_control'),
tw.Q.VarCovariate('cts_control'),
tw.Q.VarCovariate(['psi', 'alpha']),
tw.Q.VarCovariate(['cat_control', 'cts_control'])
],
'Q_cov': [
tw.Q.CovCovariate('psi', 'alpha'),
tw.Q.CovCovariate('cat_control', 'cts_control'),
tw.Q.CovCovariate(['psi', 'alpha'], ['cat_control', 'cts_control'])
],
'ncore': 8
}
)
```

You are specifying in your parameter dictionary that there is a categorical variable, so you should remove that. You can just remove `'categorical_controls': 'cat_control',` fully, or you could specify `'categorical_controls': [],`.

I did some weird things in my code for dealing with columns that start with the same name (which I plan to eventually change, since it is confusing), but I expect that the continuous controls should work in this case. However, if your columns have different names, you need to specify each column separately, e.g. if they are `'age'` and `'height'`, you would want to specify `'continuous_controls': ['age', 'height'],`.

You also need to check the bias-corrected variances/covariances you are estimating, e.g. `tw.Q.VarCovariate('cat_control'),` needs to be removed.

If you still can't get your code working, send me another update and I'll take a look again.

**Comment by klintmane1** [comment] 2022-10-26 20:16
With the following parameters:
```
# FE

fecontrol_params = tw.fecontrol_params(
    {
        'he': True,
        'categorical_controls': [],
        'continuous_controls': 'cts_control',
        'Q_var': [
            tw.Q.VarCovariate('psi'),
            tw.Q.VarCovariate('alpha'),
            tw.Q.VarCovariate('cts_control'),
            tw.Q.VarCovariate(['psi', 'alpha'])
                 ],
        'Q_cov': [
            tw.Q.CovCovariate('psi', 'alpha'),
            tw.Q.CovCovariate(['psi', 'alpha'], ['cts_control'])
        ],
        'ncore': 8
    }
)

```
Here is the error I get: 
![Screen Shot 2022-10-26 at 4 14 18 PM](https://user-images.githubusercontent.com/64566056/198127785-17c066c1-6d48-4cb4-bda1-799adf285980.png)

**Comment by klintmane1** [comment] 2022-10-26 20:18
Dropping this one does not solve it either: tw.Q.CovCovariate(['psi', 'alpha'], ['cts_control'])

**Comment by adamoppenheimer** [comment] 2022-10-26 20:22
Try this:

```python
# FE

fecontrol_params = tw.fecontrol_params(
    {
        'he': True,
        'categorical_controls': [],
        'continuous_controls': 'cts_control',
        'Q_var': [
            tw.Q.VarCovariate('psi'),
            tw.Q.VarCovariate('alpha'),
            tw.Q.VarCovariate('cts_control1'),
            tw.Q.VarCovariate('cts_control2'),
            tw.Q.VarCovariate('cts_control3'),
            tw.Q.VarCovariate(['psi', 'alpha'])
                 ],
        'Q_cov': [
            tw.Q.CovCovariate('psi', 'alpha'),
            tw.Q.CovCovariate(['psi', 'alpha'], ['cts_control1'])
        ],
        'ncore': 8
    }
)
```

I think when you compute the variances/covariances you need to estimate each control variable separately.

Let me know if this works.

**Comment by klintmane1** [comment] 2022-10-26 20:29
That worked perfectly! Will give it a try on true data. One more question: Can the CRE model be estimated with controls?

**Comment by klintmane1** [comment] 2022-10-26 20:58
This is what I get on real data. Any suggestions?

![Screen Shot 2022-10-26 at 4 58 11 PM](https://user-images.githubusercontent.com/64566056/198136442-53538a99-828e-4b3c-a330-82d2387fa842.png)

**Comment by adamoppenheimer** [comment] 2022-10-26 21:05
That's a warning not an error, you can ignore it so long as the estimator still runs.

If it bothers you, you can change the preconditioner parameters to start with a larger shift (like the warning says), but I think it's better to just keep it as-is.

You can also change your preconditioner, I would suggest trying the Jacobi preconditioner. But I set it to the incomplete Cholesky decomposition by default since it seems to be the fastest in practice with reasonably sized datasets.

Regarding your previous question, the CRE estimator does not allow controls. I have thought about adding it, feel free to post an issue suggesting that I add the option if you would like me to consider adding it in the future.

I am going to close this issue since it seems your original question has been resolved.

Edit: I removed the mention of the amg solver because I wasn't thinking straight, amg is a solver not a preconditioner

**Closed as completed by adamoppenheimer** 2022-10-26 21:05 UTC

**Comment by klintmane1** [comment] 2022-10-26 21:10
Got it! I think however, the model is not producing any results. Maybe due to the warning. 
![Screen Shot 2022-10-26 at 5 10 10 PM](https://user-images.githubusercontent.com/64566056/198138879-440252d5-8ca7-4cdf-9ee2-a9e68a3f0ef2.png)

**Comment by adamoppenheimer** [comment] 2022-10-26 22:02
If you believe the issue is being caused by the incomplete Cholesky preconditioner, please try the Jacobi preconditioner.

You can do this by specifying inside your FE parameter dictionary:
```python
'preconditioner': 'jacobi'
```

**Comment by klintmane1** [comment] 2022-10-27 15:28
That did fix it! Thank you so much Adam. You have been a great help!
